# Generated by Django 2.0.13 on 2020-07-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200722_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='text_a',
        ),
        migrations.AddField(
            model_name='post',
            name='text_b',
            field=models.TextField(default='no text'),
            preserve_default=False,
        ),
    ]
