# Generated by Django 2.0.13 on 2020-07-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200722_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_link',
            field=models.CharField(default='no_text', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='text_a',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_b',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(),
        ),
    ]
