# Generated by Django 2.0.13 on 2020-07-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200722_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_alt',
            field=models.CharField(default='image', max_length=200),
            preserve_default=False,
        ),
    ]
