# Generated by Django 2.0.13 on 2020-07-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_img_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='index',
            field=models.CharField(default='NaN', max_length=4),
            preserve_default=False,
        ),
    ]
