# Generated by Django 2.0.13 on 2020-08-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200725_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_c',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='text_d',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
